name: Latest Docker CI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%APP_VERSION%%"
          replace: ${{ steps.previoustag.outputs.tag }}
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: docker/Dockerfile
          pull: false
          push: true
          tags: |
            ghcr.io/admiralfrijoles/wordle:next
            ghcr.io/admiralfrijoles/wordle:${{ steps.previoustag.outputs.tag }}
