name: Latest Docker CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: semver

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set App Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%APP_VERSION%%"
          replace: ${{ github.event_name != 'workflow_dispatch' && steps.previoustag.outputs.tag || github.event.inputs.version }}
          regex: false

      - name: Set Git Hash
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%GIT_HASH%%"
          replace: ${{ env.COMMIT_SHORT_SHA }}
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          pull: false
          push: true
          tags: |
            ghcr.io/admiralfrijoles/dojowordle:latest
            ghcr.io/admiralfrijoles/dojowordle:${{ github.event_name != 'workflow_dispatch' && steps.previoustag.outputs.tag || github.event.inputs.version }}