name: Latest Docker CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: semver

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set App Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%APP_VERSION%%"
          replace: ${{ github.event_name != 'workflow_dispatch' && steps.previoustag.outputs.tag || github.event.inputs.version }}
          regex: false

      - name: Set Release Date
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%APP_RELEASE_DATE%%"
          replace: ${{ env.RELEASE_DATE }}
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Metadata action
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/admiralfrijoles/dojowordle
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=${{ steps.previoustag.outputs.tag }},enabled=${{ github.event_name != 'workflow_dispatch' }}
            type=raw,value=latest
            type=raw,value=release,enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          pull: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}