name: Latest Docker CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: semver

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set App Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%APP_VERSION%%"
          replace: ${{ github.event_name != 'workflow_dispatch' && steps.previoustag.outputs.tag || github.event.inputs.version }}
          regex: false

      - name: Set Git Hash
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "%%GIT_HASH%%"
          replace: ${{ env.hash }}
          regex: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: Dockerfile
          pull: false
          push: true
          tags: |
            ghcr.io/admiralfrijoles/dojowordle:latest
            ghcr.io/admiralfrijoles/dojowordle:${{ steps.previoustag.outputs.tag }}

      - name: Trigger webhook
        uses: magdemajt/trigger-webhook@v1
        with:
          url: '${{ secrets.WATCHTOWER_SERVICE_URL }}'
          headers: '{"Authorization": "${{ secrets.WATCHTOWER_SERVICE_TOKEN }}"}'